---
- name: Install EPEL repository
  yum:
    name: epel-release
    state: installed

- name: Install required packages for selected NetBox configuration
  yum:
    name: "{{ _netbox_yum_packages | flatten }}"
    state: latest
    update_cache: yes
  vars:
    _netbox_yum_packages:
      - "{{ netbox_python_packages }}"
      - "{{ netbox_packages }}"
      - "{{ netbox_ldap_packages if netbox_ldap_enabled else [] }}"
      - "{{ 'git' if netbox_git else [] }}"
      - "{{ 'acl' if ('SUDO_USER' in ansible_env and ansible_env.SUDO_USER != 'root') else [] }}"
