---
- hosts: netbox
  become: yes
  vars:
    netbox_stable: true
    netbox_database_socket: "{{ postgresql_unix_socket_directories[0] }}"
    netbox_superuser_password: netbox
    netbox_socket: "0.0.0.0:80"
    netbox_config:
      ALLOWED_HOSTS:
        - localhost
        - 127.0.0.1
        - "{{ inventory_hostname }}"
      MEDIA_ROOT: "{{ netbox_shared_path }}/media"
      REPORTS_ROOT: "{{ netbox_shared_path }}/reports"
    postgresql_users:
      - name: netbox
        role_attr_flags: CREATEDB,NOSUPERUSER
  
  pre_tasks:
    - name: Enable Subscription Manager Repos
      rhsm_repository:
        name: "{{ item }}"
      loop:
        - rhel-*-optional-rpms
        - rhel-*-extras-rpms
    - name: Enable/Install EPEL Repo
      yum:
        name: https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
      
  roles:
    - geerlingguy.postgresql
    - lae.netbox

# Using this playbook installs the EPEL repo on the host
# Use at your own risk